module GameSearch.View exposing (view)

import GameSearch.Model exposing (Model)
import Html exposing (Html, div, form, input, label, text)
import Html.Attributes exposing (action, class, for, id, name, type_, value)


view : Model -> Html msg
view _ =
    div [ class "grid-x grid-margin-x" ]
        [ div [ class "medium-6 cell" ]
            [ div [ class "callout" ]
                [ form [ action "post" ]
                    [ div [ class "grid-x grid-padding-x" ]
                        [ div [ class "cell medium-6" ]
                            [ label [ for "white" ]
                                [ text "White" ]
                            , input [ name "white", type_ "text" ]
                                []
                            , text "          "
                            ]
                        , div [ class "cell medium-6" ]
                            [ label [ for "black" ]
                                [ text "Black" ]
                            , input [ name "black", type_ "text" ]
                                []
                            , text "          "
                            ]
                        ]
                    , div [ class "grid-x grid-padding-x" ]
                        [ div [ class "cell medium-6" ]
                            [ label [ for "black" ]
                                [ text "Either colour" ]
                            , input [ name "either_colour", type_ "text" ]
                                []
                            , text "          "
                            ]
                        ]
                    , div [ class "grid-x grid-padding-x" ]
                        [ div [ class "cell medium-6" ]
                            [ label [ for "min_elo" ]
                                [ text "Minimum ELO" ]
                            , input [ name "min_elo", type_ "text" ]
                                []
                            , text "          "
                            ]
                        , div [ class "cell medium-6" ]
                            [ label [ for "man_elo" ]
                                [ text "Maximum ELO" ]
                            , input [ name "man_elo", type_ "text" ]
                                []
                            , text "          "
                            ]
                        ]
                    , div [ class "grid-x grid-padding-x" ]
                        [ div [ class "cell medium-6" ]
                            [ label [ for "min_elo" ]
                                [ text "Event" ]
                            , input [ name "event", type_ "text" ]
                                []
                            , text "          "
                            ]
                        , div [ class "cell medium-6" ]
                            [ label [ for "man_elo" ]
                                [ text "Site" ]
                            , input [ name "site", type_ "text" ]
                                []
                            , text "          "
                            ]
                        ]
                    , div [ class "grid-x grid-padding-x" ]
                        [ div [ class "cell medium-6" ]
                            [ label [ for "min_elo" ]
                                [ text "Date" ]
                            , input [ name "date", type_ "text" ]
                                []
                            , text "          "
                            ]
                        , div [ class "cell medium-6" ]
                            [ label [ for "man_elo" ]
                                [ text "Round" ]
                            , input [ name "round", type_ "text" ]
                                []
                            , text "          "
                            ]
                        ]
                    , div [ class "grid-x grid-padding-x" ]
                        [ div [ class "cell medium-6" ]
                            [ label [ for "min_elo" ]
                                [ text "Result" ]
                            , input [ name "result", type_ "text" ]
                                []
                            , text "          "
                            ]
                        , div [ class "cell medium-6" ]
                            [ label [ for "man_elo" ]
                                [ text "ECO" ]
                            , input [ name "eco", type_ "text" ]
                                []
                            , text "          "
                            ]
                        ]
                    , input [ class "button", type_ "submit", value "Submit" ]
                        []
                    ]
                ]
            ]
        , div [ class "medium-6 cell" ]
            [ div [ class "callout" ]
                [ text "Results...    " ]
            ]
        ]
