require 'shellwords'

js='application.js'
copied = "../assets/js/#{js}"

elmfiles = Dir['**/*.elm']
toplevels = Shellwords.join(['src/GameViewer.elm',
                             'src/PositionSearch.elm',
                             'src/GameSearch.elm',
                             'src/MoveExplorer.elm'])

task :default => :build

desc "Compiles elm into #{js}"
task :build => js

file js => elmfiles do
  sh "elm make --optimize #{toplevels} --output=#{js}"
end

desc 'Copies the build into the assets folder'
task :copy => copied

file copied => js do
  cp js, "../assets/js/#{js}"
end
